/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class brian_com_jnidemowithgradle_Jni */

#ifndef _Included_brian_com_jnidemowithgradle_Jni
#define _Included_brian_com_jnidemowithgradle_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     brian_com_jnidemowithgradle_Jni
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_brian_com_jnidemowithgradle_Jni_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
